name: Docker runtime

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ main ]


jobs:
  build-and-publish:
    # https://github.community/t/ref-head-in-reusable-workflows/203690/30
    uses: r2d2bzh/docker-build-nodejs/.github/workflows/docker-publish.yaml@main
    with:
      image_name_suffix: runtime
