name: Docker runtime


on:
  workflow_run:
    workflows: [Test]
    types: [completed]


jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # https://github.community/t/ref-head-in-reusable-workflows/203690/30
    uses: r2d2bzh/docker-build-nodejs/.github/workflows/docker-publish.yaml@main
    with:
      image_name_suffix: runtime
