name: Docker builder


on:
  workflow_run:
    workflows: [Test]
    types: [completed]


jobs:
  on-success:
    # https://github.community/t/ref-head-in-reusable-workflows/203690/30
    uses: r2d2bzh/docker-build-nodejs/.github/workflows/docker-publish.yaml@main
    with:
      image_name_suffix: builder
