name: Test and build


on:

  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]

  pull_request:
    branches: [ main ]


jobs:

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build base images
        run: . ./ensure-compose-env.sh && docker-compose build builder runtime

      - name: Build test images
        run: . ./ensure-compose-env.sh && docker-compose --profile test build

      - name: Run test suite
        run: . ./ensure-compose-env.sh && docker-compose run --rm test

      - name: Tear down containers
        if: always()
        run: . ./ensure-compose-env.sh && docker-compose down

  builder:
    needs: test
    # https://github.community/t/ref-head-in-reusable-workflows/203690/30
    uses: r2d2bzh/docker-build-nodejs/.github/workflows/docker-publish.yaml@main
    with:
      image_name_suffix: builder

  devenv:
    needs: test
    # https://github.community/t/ref-head-in-reusable-workflows/203690/30
    uses: r2d2bzh/docker-build-nodejs/.github/workflows/docker-publish.yaml@main
    with:
      image_name_suffix: devenv

  runtime:
    needs: test
    # https://github.community/t/ref-head-in-reusable-workflows/203690/30
    uses: r2d2bzh/docker-build-nodejs/.github/workflows/docker-publish.yaml@main
    with:
      image_name_suffix: runtime

  trivy:
    needs: runtime
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-18.04
    steps:
      - name: Run Trivy on runtime image
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          image-ref: 'ghcr.io/r2d2bzh/docker-build-nodejs-runtime:${{ github.ref_name }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
